services:
  web:
    build: .
    container_name: nov-svetovni-red-web
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=www.mejmosefajn.org
      - LETSENCRYPT_HOST=www.mejmosefajn.org
    networks:
      - webproxy

networks:
  webproxy:
    external: true
